import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import PageShell from '../components/PageShell';
const PERKS = [
    ['⚡', 'Faster Support', 'Priority assistance through our partnered brokers.'],
    ['🎁', 'Trading Bonuses', 'Exclusive deposit bonuses for AFRIFX students.'],
    ['🎓', 'Educational Support', 'Extra learning resources tied to your account.'],
    ['🏆', 'Trade Challenges', 'Entry into funded and demo trading competitions.'],
    ['🔥', 'Exclusive Promotions', 'Member-only offers and seasonal promos.'],
];
export default function PartnerBroker() {
    return (_jsxs(PageShell, { title: "Broker Partnership", subtitle: "Open a trading account with our partnered brokers and unlock student perks.", children: [_jsxs("div", { className: "card", style: { background: 'linear-gradient(135deg,rgba(26,107,60,0.15),rgba(201,168,76,0.08))', border: '1px solid rgba(201,168,76,0.25)', marginBottom: 24, textAlign: 'center', padding: '40px 24px' }, children: [_jsx("div", { style: { fontSize: '2.5rem', marginBottom: 12 }, children: "\uD83E\uDD1D" }), _jsx("h2", { style: { fontFamily: "'Playfair Display',serif", fontSize: '1.5rem', fontWeight: 800, marginBottom: 10 }, children: "Trade with AFRIFX's Trusted Brokers" }), _jsx("p", { style: { color: '#c8c8c8', maxWidth: 540, margin: '0 auto 20px', lineHeight: 1.7 }, children: "Students who open accounts through our partnered brokers enjoy faster support, bonuses, and exclusive educational perks." }), _jsx("a", { href: "#contact-broker", className: "btn btn-gold", children: "Request Broker Details" })] }), _jsx("h2", { style: { fontSize: '1.1rem', fontWeight: 700, marginBottom: 16 }, children: "What You Get" }), _jsx("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(220px,1fr))', gap: 16, marginBottom: 32 }, children: PERKS.map(([icon, title, desc]) => (_jsxs("div", { className: "card", style: { display: 'flex', gap: 14, alignItems: 'flex-start' }, children: [_jsx("span", { style: { fontSize: '1.6rem', flexShrink: 0 }, children: icon }), _jsxs("div", { children: [_jsx("div", { style: { fontWeight: 700, fontSize: '0.92rem' }, children: title }), _jsx("div", { style: { fontSize: '0.82rem', color: '#9a9a9a', marginTop: 2 }, children: desc })] })] }, title))) }), _jsxs("div", { id: "contact-broker", className: "card", style: { textAlign: 'center', padding: 32 }, children: [_jsx("h3", { style: { fontWeight: 700, marginBottom: 8 }, children: "Ready to open an account?" }), _jsx("p", { style: { color: '#9a9a9a', marginBottom: 20 }, children: "Contact our team for the latest partnered broker links and onboarding help." }), _jsxs("div", { style: { display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }, children: [_jsx(Link, { to: "/meetings", className: "btn btn-outline", children: "Book a Session" }), _jsx("a", { href: "mailto:partners@afrifxacademy.com", className: "btn btn-gold", children: "Email Partnerships" })] })] })] }));
}
