import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { api } from '../api';
import PageShell from '../components/PageShell';
import Donut from '../components/charts/Donut';
export default function Performance() {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [view, setView] = useState('monthly');
    const [page, setPage] = useState(0);
    const PAGE_SIZE = 15;
    useEffect(() => { api.signalPerformance().then(setData).finally(() => setLoading(false)); }, []);
    if (loading)
        return _jsx(PageShell, { title: "Performance Dashboard", subtitle: "Transparent, verifiable results from our published trading signals.", children: _jsx("div", { className: "loading-center", children: _jsx("span", { className: "spinner" }) }) });
    if (!data || data.trades === 0)
        return (_jsx(PageShell, { title: "Performance Dashboard", subtitle: "Transparent, verifiable results from our published trading signals.", children: _jsxs("div", { className: "card", style: { textAlign: 'center', padding: 48 }, children: [_jsx("p", { style: { fontSize: '2.5rem', marginBottom: 12 }, children: "\uD83D\uDCCA" }), _jsx("h3", { children: "No closed trades yet" }), _jsx("p", { style: { color: '#9a9a9a', marginTop: 8 }, children: "Once signals are closed with results, full performance stats appear here." })] }) }));
    const chartData = view === 'monthly' ? data.months : data.weeks;
    const maxAbs = Math.max(1, ...chartData.map((m) => Math.abs(m.pips)));
    const history = data.history || [];
    const pageSlice = history.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);
    const totalPages = Math.ceil(history.length / PAGE_SIZE);
    return (_jsxs(PageShell, { title: "Performance Dashboard", subtitle: "Transparent, verifiable results from our published trading signals.", children: [_jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 20 }, children: [_jsxs("div", { className: "card", style: { display: 'flex', alignItems: 'center', gap: 14, background: 'linear-gradient(120deg,rgba(14,203,129,0.08),rgba(26,107,60,0.06))', border: '1px solid rgba(14,203,129,0.2)', padding: '14px 20px' }, children: [_jsx("span", { style: { fontSize: '1.6rem' }, children: "\uD83D\uDD12" }), _jsxs("div", { children: [_jsx("div", { style: { fontWeight: 700, fontSize: '0.9rem' }, children: "100% Transparent Performance" }), _jsx("div", { style: { fontSize: '0.78rem', color: '#9a9a9a' }, children: "All results are from live, publicly published signals. Nothing is hidden or adjusted." })] })] }), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(170px,1fr))', gap: 16 }, children: [_jsx(Kpi, { icon: "\uD83C\uDFAF", value: `${data.winRate}%`, label: "Win Rate", tint: "#0ecb81" }), _jsx(Kpi, { icon: "\uD83D\uDCC8", value: (data.totalPips >= 0 ? '+' : '') + data.totalPips, label: "Total Pips", tint: data.totalPips >= 0 ? '#0ecb81' : '#f6465d' }), _jsx(Kpi, { icon: "\uD83D\uDCCA", value: data.trades, label: "Total Trades", tint: "#c9a84c" }), _jsx(Kpi, { icon: "\u2705", value: data.wins, label: "Wins", tint: "#0ecb81" }), _jsx(Kpi, { icon: "\u274C", value: data.losses, label: "Losses", tint: "#f6465d" }), _jsx(Kpi, { icon: "\u2696\uFE0F", value: data.rr ? `1:${data.rr}` : '—', label: "Risk : Reward", tint: "#4aa3d4" }), _jsx(Kpi, { icon: "\uD83D\uDCC9", value: data.avgWin ? `${data.avgWin} pips` : '—', label: "Avg Win", tint: "#0ecb81" }), _jsx(Kpi, { icon: "\uD83D\uDCC9", value: data.avgLoss ? `${data.avgLoss} pips` : '—', label: "Avg Loss", tint: "#f6465d" })] }), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: 'minmax(0,2fr) minmax(0,1fr)', gap: 20 }, className: "perf-grid", children: [_jsxs("div", { className: "card card-premium", children: [_jsxs("div", { style: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }, children: [_jsx("h3", { style: { fontWeight: 700, fontSize: '1rem' }, children: "Pips Performance" }), _jsx("div", { style: { display: 'flex', gap: 6 }, children: ['weekly', 'monthly'].map(v => (_jsx("button", { onClick: () => setView(v), className: `btn btn-sm ${view === v ? 'btn-gold' : 'btn-outline'}`, children: v === 'weekly' ? 'Weekly' : 'Monthly' }, v))) })] }), _jsx("div", { style: { display: 'flex', alignItems: 'flex-end', gap: 10, height: 200, paddingBottom: 8 }, children: chartData.map((m) => {
                                            const pos = m.pips >= 0;
                                            const h = (Math.abs(m.pips) / maxAbs) * 100;
                                            return (_jsxs("div", { style: { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, height: '100%', justifyContent: 'flex-end' }, children: [_jsxs("span", { className: "mono", style: { fontSize: '0.7rem', color: pos ? 'var(--up)' : 'var(--down)', fontWeight: 700 }, children: [pos ? '+' : '', m.pips] }), _jsx("div", { style: { width: '100%', height: `${Math.max(h, 2)}%`, background: pos ? 'linear-gradient(180deg,#0ecb81,rgba(14,203,129,0.5))' : 'linear-gradient(180deg,#f6465d,rgba(246,70,93,0.5))', borderRadius: '4px 4px 0 0', transition: 'height 0.4s' } }), _jsx("div", { style: { fontSize: '0.66rem', color: '#9a9a9a', textAlign: 'center' }, children: m.label }), m.trades > 0 && _jsxs("div", { style: { fontSize: '0.6rem', color: '#666' }, children: [m.trades, "T"] })] }, m.label));
                                        }) })] }), _jsxs("div", { className: "card card-premium", style: { display: 'flex', flexDirection: 'column' }, children: [_jsx("h3", { style: { fontWeight: 700, fontSize: '1rem', marginBottom: 16 }, children: "Win / Loss" }), _jsx("div", { style: { flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }, children: _jsx(Donut, { size: 160, centerTop: "Win Rate", centerBottom: `${data.winRate}%`, segments: [
                                                { label: `Wins (${data.wins})`, value: data.wins, color: '#0ecb81' },
                                                { label: `Losses (${data.losses})`, value: data.losses, color: '#f6465d' },
                                                { label: `Breakeven (${data.breakeven})`, value: data.breakeven, color: '#c9a84c' },
                                            ] }) }), _jsxs("div", { style: { marginTop: 12, display: 'flex', flexDirection: 'column', gap: 6 }, children: [[{ label: 'Wins', val: data.wins, col: 'var(--up)' }, { label: 'Losses', val: data.losses, col: 'var(--down)' }, { label: 'Breakeven', val: data.breakeven, col: '#c9a84c' }].map(r => (_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem' }, children: [_jsx("span", { style: { color: '#9a9a9a' }, children: r.label }), _jsx("span", { className: "mono", style: { color: r.col, fontWeight: 700 }, children: r.val })] }, r.label))), data.rr > 0 && (_jsxs("div", { style: { marginTop: 8, padding: '10px 12px', background: 'rgba(74,163,212,0.1)', border: '1px solid rgba(74,163,212,0.25)', borderRadius: 8, textAlign: 'center' }, children: [_jsx("div", { style: { fontSize: '0.7rem', color: '#9a9a9a' }, children: "Risk : Reward" }), _jsxs("div", { className: "mono", style: { fontSize: '1.2rem', fontWeight: 800, color: '#4aa3d4' }, children: ["1 : ", data.rr] })] }))] })] })] }), _jsxs("div", { className: "card card-premium", children: [_jsxs("div", { style: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }, children: [_jsx("h3", { style: { fontWeight: 700, fontSize: '1rem' }, children: "\uD83D\uDCC1 Historical Archive" }), _jsxs("span", { style: { fontSize: '0.76rem', color: '#9a9a9a' }, children: [history.length, " closed signals"] })] }), _jsx("div", { className: "table-wrap", children: _jsxs("table", { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Pair" }), _jsx("th", { children: "Direction" }), _jsx("th", { children: "Entry" }), _jsx("th", { children: "SL" }), _jsx("th", { children: "TP1" }), _jsx("th", { children: "Pips" }), _jsx("th", { children: "Result" }), _jsx("th", { children: "Date" })] }) }), _jsx("tbody", { children: pageSlice.map((s) => {
                                                const win = s.result === 'win';
                                                const loss = s.result === 'loss';
                                                const col = win ? 'var(--up)' : loss ? 'var(--down)' : '#c9a84c';
                                                return (_jsxs("tr", { children: [_jsx("td", { style: { fontWeight: 700 }, children: s.pair }), _jsx("td", { children: _jsx("span", { style: { fontSize: '0.72rem', padding: '2px 8px', borderRadius: 20, color: s.direction === 'BUY' ? 'var(--up)' : 'var(--down)', background: s.direction === 'BUY' ? 'rgba(14,203,129,0.1)' : 'rgba(246,70,93,0.1)', border: `1px solid ${s.direction === 'BUY' ? 'rgba(14,203,129,0.3)' : 'rgba(246,70,93,0.3)'}` }, children: s.direction }) }), _jsx("td", { className: "mono", style: { fontSize: '0.82rem' }, children: s.entry }), _jsx("td", { className: "mono", style: { fontSize: '0.82rem', color: 'var(--down)' }, children: s.stopLoss }), _jsx("td", { className: "mono", style: { fontSize: '0.82rem', color: 'var(--up)' }, children: s.tp1 }), _jsx("td", { className: "mono", style: { fontWeight: 700, color: col }, children: s.pips != null ? `${win ? '+' : loss ? '-' : ''}${Math.abs(s.pips)}` : '—' }), _jsx("td", { children: _jsx("span", { style: { fontSize: '0.7rem', padding: '2px 8px', borderRadius: 20, color: col, background: `${col}18`, border: `1px solid ${col}33`, textTransform: 'capitalize' }, children: s.result || '—' }) }), _jsx("td", { style: { color: '#9a9a9a', fontSize: '0.78rem' }, children: new Date(s.createdAt).toLocaleDateString('en-GB') })] }, s.id));
                                            }) })] }) }), totalPages > 1 && (_jsxs("div", { style: { display: 'flex', justifyContent: 'center', gap: 8, marginTop: 16 }, children: [_jsx("button", { className: "btn btn-outline btn-sm", disabled: page === 0, onClick: () => setPage(p => p - 1), children: "\u2190 Prev" }), _jsxs("span", { style: { fontSize: '0.82rem', color: '#9a9a9a', alignSelf: 'center' }, children: ["Page ", page + 1, " / ", totalPages] }), _jsx("button", { className: "btn btn-outline btn-sm", disabled: page >= totalPages - 1, onClick: () => setPage(p => p + 1), children: "Next \u2192" })] }))] }), _jsx("p", { style: { textAlign: 'center', color: '#666', fontSize: '0.76rem' }, children: "Past performance does not guarantee future results. Trade responsibly." })] }), _jsx("style", { children: `@media(max-width:820px){.perf-grid{grid-template-columns:1fr!important}}` })] }));
}
function Kpi({ icon, value, label, tint }) {
    return (_jsxs("div", { className: "card card-hover", style: { position: 'relative', overflow: 'hidden' }, children: [_jsx("div", { style: { position: 'absolute', right: -16, top: -16, width: 80, height: 80, borderRadius: '50%', background: `radial-gradient(circle,${tint}22,transparent 70%)` } }), _jsx("div", { style: { width: 42, height: 42, borderRadius: 12, background: `${tint}1a`, border: `1px solid ${tint}44`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.3rem', marginBottom: 10 }, children: icon }), _jsx("div", { className: "mono", style: { fontSize: '1.6rem', fontWeight: 800, lineHeight: 1, color: tint }, children: value }), _jsx("div", { style: { fontSize: '0.78rem', color: '#9a9a9a', marginTop: 5 }, children: label })] }));
}
