import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../../api';
import DashboardLayout from '../../components/DashboardLayout';
import Donut from '../../components/charts/Donut';
export default function AdminAnalytics() {
    const [data, setData] = useState(null);
    const [stats, setStats] = useState(null);
    const [perf, setPerf] = useState(null);
    useEffect(() => {
        Promise.all([
            api.adminAnalytics(),
            api.adminStats().catch(() => null),
            api.signalPerformance().catch(() => null),
        ]).then(([a, s, p]) => { setData(a); setStats(s); setPerf(p); });
    }, []);
    if (!data)
        return _jsx(DashboardLayout, { title: "Platform Analytics", children: _jsx("div", { className: "loading-center", children: _jsx("span", { className: "spinner" }) }) });
    const maxSignup = Math.max(...data.signups.map((s) => s.count), 1);
    const maxPop = Math.max(...data.popularity.map((p) => p.enrollments), 1);
    const notStarted = Math.max(0, data.totalEnrollments - data.completedEnrollments - data.activeEnrollments);
    return (_jsxs(DashboardLayout, { title: "Platform Analytics", subtitle: "Insights into enrollment trends and course performance.", children: [_jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 20 }, children: [_jsxs("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(190px,1fr))', gap: 16 }, children: [_jsx(Kpi, { icon: "\uD83D\uDCCB", value: data.totalEnrollments, label: "Total Enrollments", tint: "#c9a84c" }), _jsx(Kpi, { icon: "\uD83D\uDD04", value: data.activeEnrollments, label: "In Progress", tint: "#4aa3d4" }), _jsx(Kpi, { icon: "\u2705", value: data.completedEnrollments, label: "Completed", tint: "#4caf50" }), _jsx(Kpi, { icon: "\uD83D\uDCCA", value: `${data.completionRate}%`, label: "Completion Rate", tint: "#e2c070", pillGold: true, pill: perf ? `${perf.winRate}% signal WR` : undefined })] }), stats && (_jsxs("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(150px,1fr))', gap: 16 }, children: [_jsx(MiniStat, { icon: "\uD83D\uDC65", value: stats.students, label: "Students", to: "/admin/students" }), _jsx(MiniStat, { icon: "\uD83D\uDCDA", value: stats.courses, label: "Courses", to: "/admin/courses" }), _jsx(MiniStat, { icon: "\uD83C\uDF93", value: stats.certs, label: "Certificates", to: "/admin/certificates" }), _jsx(MiniStat, { icon: "\uD83D\uDCE1", value: perf ? perf.trades : 0, label: "Signals Closed", to: "/admin/signals" })] })), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: 'minmax(0,2fr) minmax(0,1fr)', gap: 20 }, className: "bento-2", children: [_jsxs("div", { className: "card card-premium", children: [_jsx("h3", { style: { fontWeight: 700, fontSize: '1rem', marginBottom: 24 }, children: "\uD83D\uDCC8 New Students (6 months)" }), _jsx("div", { style: { display: 'flex', alignItems: 'flex-end', gap: 12, height: 210, paddingBottom: 8 }, children: data.signups.map((s) => (_jsxs("div", { style: { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8, height: '100%', justifyContent: 'flex-end' }, children: [_jsx("span", { style: { fontSize: '0.78rem', color: '#c9a84c', fontWeight: 700 }, children: s.count }), _jsx("div", { style: { width: '100%', height: `${(s.count / maxSignup) * 100}%`, minHeight: s.count > 0 ? 4 : 0, background: 'linear-gradient(180deg,#c9a84c,#1a6b3c)', borderRadius: '6px 6px 0 0', transition: 'height 0.5s' } }), _jsx("span", { style: { fontSize: '0.74rem', color: '#9a9a9a' }, children: s.label })] }, s.label))) })] }), _jsxs("div", { className: "card card-premium", style: { display: 'flex', flexDirection: 'column' }, children: [_jsx("h3", { style: { fontWeight: 700, fontSize: '1rem', marginBottom: 18 }, children: "Course Completion" }), _jsx("div", { style: { flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }, children: data.totalEnrollments > 0 ? (_jsx(Donut, { size: 170, centerTop: "Rate", centerBottom: `${data.completionRate}%`, segments: [
                                                { label: `Completed (${data.completedEnrollments})`, value: data.completedEnrollments, color: '#4caf50' },
                                                { label: `Active (${data.activeEnrollments})`, value: data.activeEnrollments, color: '#c9a84c' },
                                                { label: `Not Started (${notStarted})`, value: notStarted, color: '#3a3a3a' },
                                            ] })) : _jsx("p", { style: { color: '#9a9a9a', fontSize: '0.85rem' }, children: "No enrollment data yet." }) })] })] }), _jsxs("div", { className: "card card-premium", children: [_jsx("h3", { style: { fontWeight: 700, fontSize: '1rem', marginBottom: 20 }, children: "\uD83D\uDD25 Most Popular Courses" }), data.popularity.length === 0 ? _jsx("p", { style: { color: '#9a9a9a' }, children: "No enrollment data yet." }) : (_jsx("div", { style: { display: 'flex', flexDirection: 'column', gap: 16 }, children: data.popularity.map((p, i) => (_jsxs("div", { children: [_jsxs("div", { style: { display: 'flex', justifyContent: 'space-between', marginBottom: 6, fontSize: '0.86rem' }, children: [_jsxs("span", { style: { display: 'flex', alignItems: 'center', gap: 8, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: '75%' }, children: [_jsxs("span", { style: { color: '#666', fontWeight: 700, fontSize: '0.78rem' }, children: ["#", i + 1] }), p.title] }), _jsxs("span", { style: { color: '#c9a84c', fontWeight: 700 }, children: [p.enrollments, " enrolled"] })] }), _jsx("div", { className: "progress-bar-wrap", style: { height: 9 }, children: _jsx("div", { className: "progress-bar-fill", style: { width: `${(p.enrollments / maxPop) * 100}%` } }) })] }, p.title))) }))] }), _jsx("div", { className: "card", style: { background: 'linear-gradient(120deg, rgba(26,107,60,0.12), rgba(20,20,24,0.4) 60%, rgba(201,168,76,0.1))' }, children: _jsxs("p", { style: { color: '#c8c8c8', fontSize: '0.9rem', lineHeight: 1.7 }, children: [data.completedEnrollments, " of ", data.totalEnrollments, " enrollments fully completed.", data.completionRate >= 50 ? ' Great engagement! 🎉 Keep the momentum with fresh content and live sessions.' : ' Consider posting announcements or reminders to boost completion rates.'] }) })] }), _jsx("style", { children: `@media (max-width: 900px){ .bento-2 { grid-template-columns: 1fr !important; } }` })] }));
}
function Kpi({ icon, value, label, tint, pill, pillGold }) {
    return (_jsxs("div", { className: "card card-hover", style: { position: 'relative', overflow: 'hidden' }, children: [_jsx("div", { style: { position: 'absolute', right: -20, top: -20, width: 90, height: 90, borderRadius: '50%', background: `radial-gradient(circle, ${tint}22, transparent 70%)` } }), _jsxs("div", { style: { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 14 }, children: [_jsx("div", { style: { width: 46, height: 46, borderRadius: 12, background: `${tint}1a`, border: `1px solid ${tint}44`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.4rem' }, children: icon }), pill && _jsx("span", { style: { fontSize: '0.68rem', fontWeight: 700, padding: '3px 10px', borderRadius: 20, color: '#c9a84c', background: 'rgba(201,168,76,0.12)', border: '1px solid rgba(201,168,76,0.3)' }, children: pill })] }), _jsx("div", { style: { fontSize: '2rem', fontWeight: 800, lineHeight: 1 }, children: value }), _jsx("div", { style: { fontSize: '0.8rem', color: '#9a9a9a', marginTop: 6 }, children: label })] }));
}
function MiniStat({ icon, value, label, to }) {
    return (_jsxs(Link, { to: to, className: "card card-hover", style: { display: 'flex', alignItems: 'center', gap: 12, textDecoration: 'none', padding: '16px 18px' }, children: [_jsx("span", { style: { fontSize: '1.4rem' }, children: icon }), _jsxs("div", { children: [_jsx("div", { style: { fontSize: '1.4rem', fontWeight: 800, lineHeight: 1 }, children: value }), _jsx("div", { style: { fontSize: '0.74rem', color: '#9a9a9a' }, children: label })] })] }));
}
