import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
export default function AuthShell({ children, heading, sub }) {
    return (_jsxs("div", { style: { minHeight: '100vh', display: 'grid', gridTemplateColumns: '1.05fr 1fr', background: '#0a0a0b' }, className: "auth-grid", children: [_jsxs("div", { className: "auth-brand", style: {
                    position: 'relative', overflow: 'hidden', padding: '52px 56px',
                    display: 'flex', flexDirection: 'column', justifyContent: 'space-between',
                    background: 'linear-gradient(150deg, #0f4526 0%, #0b0b0d 52%, #1a1206 100%)',
                    borderRight: '1px solid rgba(201,168,76,0.15)',
                }, children: [_jsx("div", { style: { position: 'absolute', inset: 0, backgroundImage: 'radial-gradient(rgba(255,255,255,0.05) 1px, transparent 1px)', backgroundSize: '26px 26px', opacity: 0.6 } }), _jsx("div", { style: { position: 'absolute', top: -90, left: -70, width: 340, height: 340, borderRadius: '50%', background: 'radial-gradient(circle, rgba(26,107,60,0.45), transparent 70%)' } }), _jsx("div", { style: { position: 'absolute', bottom: -110, right: -90, width: 380, height: 380, borderRadius: '50%', background: 'radial-gradient(circle, rgba(201,168,76,0.28), transparent 70%)' } }), _jsx("svg", { viewBox: "0 0 400 120", preserveAspectRatio: "none", style: { position: 'absolute', left: 0, right: 0, bottom: 0, width: '100%', height: 160, opacity: 0.22 }, children: Array.from({ length: 22 }).map((_, i) => {
                            const x = 12 + i * 18;
                            const up = Math.sin(i * 1.3) > -0.1;
                            const cy = 70 - i * 1.4;
                            const bh = 14 + (i % 4) * 7;
                            const col = up ? '#4caf50' : '#ef5350';
                            return (_jsxs("g", { children: [_jsx("line", { x1: x, x2: x, y1: cy - bh - 8, y2: cy + bh + 8, stroke: col, strokeWidth: 1.4 }), _jsx("rect", { x: x - 4, y: cy - bh / 2, width: 8, height: bh, fill: col, rx: 1 })] }, i));
                        }) }), _jsxs(Link, { to: "/", style: { display: 'flex', alignItems: 'center', gap: 12, position: 'relative', zIndex: 1 }, children: [_jsx("div", { style: { width: 46, height: 46, borderRadius: 13, background: 'linear-gradient(135deg,#1a6b3c,#c9a84c)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, fontFamily: "'Playfair Display',serif", fontSize: '1.3rem', boxShadow: '0 8px 24px rgba(201,168,76,0.3)' }, children: "A" }), _jsxs("div", { children: [_jsxs("div", { style: { fontFamily: "'Playfair Display',serif", fontWeight: 800, fontSize: '1.45rem', lineHeight: 1 }, children: [_jsx("span", { style: { color: '#fff' }, children: "Afri" }), _jsx("span", { style: { color: '#c9a84c' }, children: "FX" })] }), _jsx("div", { style: { fontSize: '0.62rem', color: '#9a9a9a', letterSpacing: 3, textTransform: 'uppercase' }, children: "Academy" })] })] }), _jsxs("div", { style: { position: 'relative', zIndex: 1 }, className: "afx-fade", children: [_jsx("span", { style: { display: 'inline-block', fontSize: '0.7rem', letterSpacing: 2, textTransform: 'uppercase', color: '#c9a84c', background: 'rgba(201,168,76,0.1)', border: '1px solid rgba(201,168,76,0.3)', padding: '5px 12px', borderRadius: 20, marginBottom: 20 }, children: "\uD83C\uDF0D Empowering African Traders" }), _jsxs("h2", { style: { fontFamily: "'Playfair Display',serif", fontSize: '2.5rem', fontWeight: 800, lineHeight: 1.18, marginBottom: 16 }, children: ["Africa's Premier", _jsx("br", {}), _jsx("span", { style: { color: '#c9a84c' }, children: "Forex Trading Academy" })] }), _jsx("p", { style: { color: '#c8c8c8', fontSize: '0.98rem', lineHeight: 1.7, maxWidth: 430, marginBottom: 26 }, children: "Learn to trade from beginner to pro \u2014 daily signals, live sessions, verifiable certificates, and a community of African traders." }), _jsx("div", { style: { display: 'flex', flexDirection: 'column', gap: 12, marginBottom: 26 }, children: [
                                    ['📈', 'Structured courses — Beginner to Advanced'],
                                    ['📡', 'Daily Forex, Gold & Crypto signals'],
                                    ['🎓', 'Verifiable completion certificates'],
                                ].map(([icon, text]) => (_jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: 12, fontSize: '0.9rem', color: '#e8e8e8' }, children: [_jsx("span", { style: { width: 32, height: 32, borderRadius: 9, background: 'rgba(201,168,76,0.12)', border: '1px solid rgba(201,168,76,0.3)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }, children: icon }), text] }, text))) }), _jsxs("div", { style: { background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', backdropFilter: 'blur(8px)', borderRadius: 14, padding: '16px 18px', maxWidth: 420 }, children: [_jsx("p", { style: { fontSize: '0.88rem', color: '#e0e0e0', fontStyle: 'italic', lineHeight: 1.6, marginBottom: 10 }, children: "\u201CAfriFX took me from zero to consistently profitable. The signals and mentorship are next level.\u201D" }), _jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: 10 }, children: [_jsx("span", { style: { width: 30, height: 30, borderRadius: '50%', background: 'linear-gradient(135deg,#1a6b3c,#c9a84c)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 700, fontSize: '0.78rem' }, children: "K" }), _jsxs("div", { children: [_jsx("div", { style: { fontSize: '0.78rem', fontWeight: 700 }, children: "Kwame A." }), _jsx("div", { style: { fontSize: '0.68rem', color: '#9a9a9a' }, children: "VVIP Member \u00B7 Accra" })] }), _jsx("span", { style: { marginLeft: 'auto', color: '#c9a84c', fontSize: '0.8rem' }, children: "\u2605\u2605\u2605\u2605\u2605" })] })] })] }), _jsx("div", { style: { position: 'relative', zIndex: 1, display: 'flex', gap: 36 }, children: [['5,000+', 'Students'], ['15+', 'Countries'], ['72%', 'Win Rate']].map(([v, l]) => (_jsxs("div", { children: [_jsx("div", { style: { fontSize: '1.5rem', fontWeight: 800, color: '#c9a84c' }, children: v }), _jsx("div", { style: { fontSize: '0.74rem', color: '#9a9a9a' }, children: l })] }, l))) })] }), _jsxs("div", { style: { display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '40px 24px', position: 'relative' }, children: [_jsx("div", { style: { position: 'absolute', width: 460, height: 460, borderRadius: '50%', background: 'radial-gradient(circle, rgba(201,168,76,0.06), transparent 70%)', pointerEvents: 'none' } }), _jsxs("div", { className: "afx-fade", style: { width: '100%', maxWidth: 410, position: 'relative' }, children: [_jsx(Link, { to: "/", className: "auth-mobile-logo", style: { display: 'none', alignItems: 'center', gap: 10, justifyContent: 'center', marginBottom: 24 }, children: _jsxs("span", { style: { fontFamily: "'Playfair Display',serif", fontWeight: 800, fontSize: '1.5rem' }, children: [_jsx("span", { style: { color: '#fff' }, children: "Afri" }), _jsx("span", { style: { color: '#c9a84c' }, children: "FX" })] }) }), _jsxs("div", { style: {
                                    background: 'linear-gradient(160deg, rgba(27,27,32,0.9), rgba(20,20,24,0.9))',
                                    border: '1px solid rgba(255,255,255,0.09)',
                                    borderRadius: 20, padding: '34px 32px',
                                    boxShadow: '0 24px 60px rgba(0,0,0,0.5)',
                                    backdropFilter: 'blur(10px)',
                                    position: 'relative', overflow: 'hidden',
                                }, children: [_jsx("div", { style: { position: 'absolute', top: 0, left: 0, right: 0, height: 3, background: 'linear-gradient(90deg, transparent, #c9a84c, transparent)' } }), _jsxs("div", { style: { marginBottom: 26 }, children: [_jsx("h1", { style: { fontFamily: "'Playfair Display',serif", fontSize: '1.75rem', fontWeight: 800, marginBottom: 6, letterSpacing: '-0.5px' }, children: heading }), _jsx("p", { style: { color: '#9a9a9a', fontSize: '0.9rem' }, children: sub })] }), children] }), _jsxs("div", { style: { textAlign: 'center', marginTop: 18, fontSize: '0.74rem', color: '#666', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6 }, children: [_jsx("span", { children: "\uD83D\uDD12" }), " Secured with bank-grade encryption"] })] })] }), _jsx("style", { children: `
        @media (max-width: 880px) {
          .auth-grid { grid-template-columns: 1fr !important; }
          .auth-brand { display: none !important; }
          .auth-mobile-logo { display: flex !important; }
        }
      ` })] }));
}
