import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import DashboardLayout from './DashboardLayout';
/* Renders the dashboard shell for logged-in users, or a clean public layout
   (top bar + login/register) for prospects. Used by public-facing pages. */
export default function PageShell({ title, subtitle, actions, children }) {
    const { user } = useAuth();
    if (user) {
        return _jsx(DashboardLayout, { title: title, subtitle: subtitle, actions: actions, children: children });
    }
    return (_jsxs("div", { style: { minHeight: '100vh', background: '#0a0a0a' }, children: [_jsx("nav", { style: { position: 'sticky', top: 0, zIndex: 30, background: 'rgba(10,10,10,0.9)', backdropFilter: 'blur(12px)', borderBottom: '1px solid rgba(201,168,76,0.15)', padding: '0 24px' }, children: _jsxs("div", { style: { maxWidth: 1100, margin: '0 auto', height: 64, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }, children: [_jsxs(Link, { to: "/", style: { display: 'flex', alignItems: 'center', gap: 10 }, children: [_jsx("div", { style: { width: 36, height: 36, borderRadius: 9, background: 'linear-gradient(135deg,#1a6b3c,#c9a84c)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 800, fontFamily: "'Playfair Display',serif" }, children: "A" }), _jsxs("span", { style: { fontFamily: "'Playfair Display',serif", fontWeight: 800, fontSize: '1.2rem' }, children: [_jsx("span", { style: { color: '#fff' }, children: "Afri" }), _jsx("span", { style: { color: '#c9a84c' }, children: "FX" })] })] }), _jsxs("div", { style: { display: 'flex', gap: 10, alignItems: 'center' }, children: [_jsx(Link, { to: "/markets", style: { color: '#9a9a9a', fontSize: '0.85rem' }, children: "Markets" }), _jsx(Link, { to: "/performance", style: { color: '#9a9a9a', fontSize: '0.85rem' }, children: "Performance" }), _jsx(Link, { to: "/pricing", style: { color: '#9a9a9a', fontSize: '0.85rem' }, children: "Pricing" }), _jsx(Link, { to: "/login", className: "btn btn-outline btn-sm", children: "Login" }), _jsx(Link, { to: "/register", className: "btn btn-gold btn-sm", children: "Join Free" })] })] }) }), _jsxs("header", { style: { maxWidth: 1100, margin: '0 auto', padding: '36px 24px 12px' }, children: [_jsx("h1", { style: { fontFamily: "'Playfair Display',serif", fontSize: 'clamp(1.6rem,3vw,2.2rem)', fontWeight: 800 }, children: title }), subtitle && _jsx("p", { style: { color: '#9a9a9a', marginTop: 6 }, children: subtitle })] }), _jsx("main", { style: { maxWidth: 1100, margin: '0 auto', padding: '12px 24px 60px' }, children: children })] }));
}
